"""
Report Agent - Generates professional PDF and PowerPoint reports
Implements complete business intelligence reporting with charts, insights, and recommendations
"""

from typing import Dict, List, Optional
import os
from datetime import datetime
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt
import io
from pathlib import Path

# PDF generation
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image as RLImage, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

# PowerPoint generation
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor

# Database
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from database.models import Dashboard, Dataset
from database.db import get_db


async def generate_pdf_report(
    dashboard_id: str,
    db: AsyncSession,
    output_dir: str = "data/reports"
) -> Dict:
    """
    Generate a complete PDF business report with all sections.
    
    Returns:
        Dict with report_id, file_path, and metadata
    """
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Load dashboard and dataset
    result = await db.execute(select(Dashboard).where(Dashboard.id == dashboard_id))
    dashboard = result.scalar_one_or_none()
    if not dashboard:
        raise ValueError(f"Dashboard {dashboard_id} not found")
    
    result = await db.execute(select(Dataset).where(Dataset.id == dashboard.dataset_id))
    dataset = result.scalar_one_or_none()
    if not dataset:
        raise ValueError(f"Dataset {dashboard.dataset_id} not found")
    
    # Generate report ID and filename
    report_id = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    pdf_filename = f"{report_id}.pdf"
    pdf_path = os.path.join(output_dir, pdf_filename)
    
    # Create PDF document
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18
    )
    
    # Container for PDF elements
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # 1. COVER PAGE
    story.append(Spacer(1, 2*inch))
    story.append(Paragraph("Business Intelligence Report", title_style))
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(f"<b>Dataset:</b> {dataset.name}", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    story.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    story.append(Paragraph("<b>Generated by:</b> Talking BI - Agentic AI Platform", styles['Normal']))
    story.append(PageBreak())
    
    # 2. EXECUTIVE SUMMARY
    tiles = dashboard.tiles_json or []
    insights_tile = next((t for t in tiles if t.get('type') == 'insights'), None)
    
    story.append(Paragraph("Executive Summary", heading_style))
    
    if insights_tile and insights_tile.get('data'):
        insights_data = insights_tile['data']
        summary = insights_data.get('executive_summary', 'Analysis completed successfully.')
        story.append(Paragraph(summary, styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
        
        # Data quality indicator
        confidence = insights_data.get('overall_confidence', 0)
        quality = insights_data.get('data_quality', 'medium')
        story.append(Paragraph(
            f"<b>Data Quality:</b> {quality.title()} (Confidence: {confidence:.1f}%)",
            styles['Normal']
        ))
    else:
        story.append(Paragraph(
            "This report provides comprehensive analysis of the dataset with key performance indicators, "
            "trends, correlations, and actionable recommendations.",
            styles['Normal']
        ))
    
    story.append(Spacer(1, 0.5*inch))
    
    # 3. KEY PERFORMANCE INDICATORS
    story.append(Paragraph("Key Performance Indicators", heading_style))
    
    kpi_tiles = [t for t in tiles if t.get('type') == 'kpi']
    if kpi_tiles:
        # Create KPI table
        kpi_data = [['Metric', 'Value', 'Change', 'Status']]
        
        for kpi_tile in kpi_tiles[:10]:  # Top 10 KPIs
            kpi_info = kpi_tile.get('config', {})
            metric = kpi_tile.get('title', 'Unknown')
            value = kpi_info.get('value', 0)
            change = kpi_info.get('change', 0)
            
            # Format value
            if isinstance(value, (int, float)):
                value_str = f"{value:,.2f}"
            else:
                value_str = str(value)
            
            # Format change with arrow
            if change > 0:
                change_str = f"↑ +{change:.1f}%"
                status = "✓"
            elif change < 0:
                change_str = f"↓ {change:.1f}%"
                status = "⚠"
            else:
                change_str = "—"
                status = "—"
            
            kpi_data.append([metric, value_str, change_str, status])
        
        kpi_table = Table(kpi_data, colWidths=[2.5*inch, 1.5*inch, 1.2*inch, 0.8*inch])
        kpi_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        story.append(kpi_table)
    else:
        story.append(Paragraph("No KPI data available.", styles['Normal']))
    
    story.append(Spacer(1, 0.5*inch))
    
    # 4. CHARTS - Embed top 4 charts as PNG
    story.append(PageBreak())
    story.append(Paragraph("Visual Analysis", heading_style))
    
    chart_tiles = [t for t in tiles if t.get('type') in ['chart', 'bar', 'line', 'area', 'pie']]
    charts_embedded = 0
    
    for chart_tile in chart_tiles[:4]:  # Top 4 charts
        try:
            chart_config = chart_tile.get('config', {})
            chart_title = chart_tile.get('title', 'Chart')
            
            # Generate matplotlib chart
            chart_image = await _generate_chart_image({}, chart_config, chart_title)
            
            if chart_image:
                story.append(Paragraph(chart_title, styles['Heading3']))
                story.append(Spacer(1, 0.1*inch))
                story.append(chart_image)
                story.append(Spacer(1, 0.3*inch))
                charts_embedded += 1
                
                # Add page break after 2 charts
                if charts_embedded % 2 == 0 and charts_embedded < 4:
                    story.append(PageBreak())
        except Exception as e:
            print(f"Error embedding chart '{chart_title}': {e}")
            import traceback
            traceback.print_exc()
            continue
    
    if charts_embedded == 0:
        story.append(Paragraph("No charts available for embedding.", styles['Normal']))
    
    story.append(Spacer(1, 0.3*inch))
    
    # 5. KEY INSIGHTS
    story.append(PageBreak())
    story.append(Paragraph("Key Insights", heading_style))
    
    if insights_tile and insights_tile.get('data'):
        insights_data = insights_tile['data']
        key_insights = insights_data.get('key_insights', [])
        
        if key_insights:
            for i, insight in enumerate(key_insights[:5], 1):
                story.append(Paragraph(f"<b>{i}.</b> {insight}", styles['Normal']))
                story.append(Spacer(1, 0.15*inch))
        else:
            story.append(Paragraph("No specific insights generated.", styles['Normal']))
    else:
        story.append(Paragraph("No insights data available.", styles['Normal']))
    
    story.append(Spacer(1, 0.5*inch))
    
    # 6. WATCH OUT ITEMS
    story.append(Paragraph("Watch Out Items", heading_style))
    
    if insights_tile and insights_tile.get('data'):
        watch_out = insights_tile['data'].get('watch_out', [])
        
        if watch_out:
            for i, item in enumerate(watch_out[:3], 1):
                story.append(Paragraph(f"<b>⚠ {i}.</b> {item}", styles['Normal']))
                story.append(Spacer(1, 0.15*inch))
        else:
            story.append(Paragraph("No critical items identified.", styles['Normal']))
    else:
        story.append(Paragraph("No watch-out data available.", styles['Normal']))
    
    story.append(Spacer(1, 0.5*inch))
    
    # 7. RECOMMENDATIONS
    story.append(PageBreak())
    story.append(Paragraph("Strategic Recommendations", heading_style))
    
    recommendations_tile = next((t for t in tiles if t.get('type') == 'recommendations'), None)
    
    if recommendations_tile and recommendations_tile.get('data'):
        recommendations = recommendations_tile['data'].get('recommendations', [])
        
        if recommendations:
            for i, rec in enumerate(recommendations[:3], 1):
                story.append(Paragraph(f"<b>Recommendation {i}:</b> {rec.get('action', 'N/A')}", styles['Heading4']))
                story.append(Spacer(1, 0.1*inch))
                
                # Details table
                rec_data = [
                    ['Expected Impact', rec.get('expected_impact', 'N/A')],
                    ['Timeline', rec.get('timeline', 'N/A')],
                    ['Risk Level', rec.get('risk', 'N/A')],
                    ['Priority', rec.get('priority', 'N/A')]
                ]
                
                rec_table = Table(rec_data, colWidths=[2*inch, 4*inch])
                rec_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ]))
                
                story.append(rec_table)
                story.append(Spacer(1, 0.3*inch))
        else:
            story.append(Paragraph("No recommendations generated.", styles['Normal']))
    else:
        story.append(Paragraph("No recommendations data available.", styles['Normal']))
    
    story.append(Spacer(1, 0.5*inch))
    
    # 8. ROOT CAUSE ANALYSIS (if available)
    root_cause_tile = next((t for t in tiles if t.get('type') == 'root_cause'), None)
    
    if root_cause_tile and root_cause_tile.get('data'):
        story.append(PageBreak())
        story.append(Paragraph("Root Cause Analysis", heading_style))
        
        root_cause_data = root_cause_tile['data']
        
        # Metric change
        metric = root_cause_data.get('metric', 'Unknown')
        change = root_cause_data.get('change_pct', 0)
        story.append(Paragraph(
            f"<b>Metric:</b> {metric} changed by {change:+.1f}%",
            styles['Normal']
        ))
        story.append(Spacer(1, 0.2*inch))
        
        # Top contributors
        contributors = root_cause_data.get('top_contributors', [])
        if contributors:
            story.append(Paragraph("<b>Top Contributing Factors:</b>", styles['Normal']))
            story.append(Spacer(1, 0.1*inch))
            
            for i, contrib in enumerate(contributors[:5], 1):
                story.append(Paragraph(
                    f"{i}. {contrib.get('segment', 'N/A')}: {contrib.get('contribution_pct', 0):+.1f}% "
                    f"(Confidence: {contrib.get('confidence', 0):.0f}%)",
                    styles['Normal']
                ))
                story.append(Spacer(1, 0.1*inch))
        
        # Narrative
        narrative = root_cause_data.get('narrative', '')
        if narrative:
            story.append(Spacer(1, 0.2*inch))
            story.append(Paragraph("<b>Analysis:</b>", styles['Normal']))
            story.append(Paragraph(narrative, styles['Normal']))
    
    story.append(Spacer(1, 0.5*inch))
    
    # 9. APPENDIX - Data Cleaning Log
    story.append(PageBreak())
    story.append(Paragraph("Appendix: Data Processing", heading_style))
    
    cleaning_log = dataset.cleaning_log or []
    if cleaning_log:
        story.append(Paragraph("<b>Data Cleaning Actions:</b>", styles['Normal']))
        story.append(Spacer(1, 0.1*inch))
        
        for i, action in enumerate(cleaning_log[:10], 1):
            action_text = action if isinstance(action, str) else str(action)
            story.append(Paragraph(f"{i}. {action_text}", styles['Normal']))
            story.append(Spacer(1, 0.05*inch))
    else:
        story.append(Paragraph("No data cleaning actions recorded.", styles['Normal']))
    
    story.append(Spacer(1, 0.3*inch))
    
    # Dataset metadata
    story.append(Paragraph("<b>Dataset Information:</b>", styles['Normal']))
    story.append(Spacer(1, 0.1*inch))
    
    metadata_data = [
        ['Rows', str(dataset.row_count or 0)],
        ['Columns', str(dataset.column_count or 0)],
        ['Source Type', dataset.source_type or 'Unknown'],
        ['Created', dataset.created_at.strftime('%Y-%m-%d %H:%M') if dataset.created_at else 'Unknown']
    ]
    
    metadata_table = Table(metadata_data, colWidths=[2*inch, 4*inch])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    
    story.append(metadata_table)
    
    # Build PDF
    doc.build(story)
    
    # Save report metadata to database
    from database.models import Report
    report_record = Report(
        report_id=report_id,
        dashboard_id=dashboard_id,
        dataset_id=dataset.id,
        format="pdf",
        pdf_path=pdf_path,
        metadata_json={
            "page_count": len(story),
            "charts_embedded": charts_embedded,
            "dataset_name": dataset.name
        }
    )
    db.add(report_record)
    await db.commit()
    
    return {
        "report_id": report_id,
        "file_path": pdf_path,
        "format": "pdf",
        "dashboard_id": dashboard_id,
        "dataset_name": dataset.name,
        "generated_at": datetime.now().isoformat(),
        "page_count": len(story),
        "charts_embedded": charts_embedded
    }


async def _generate_chart_image(
    chart_data: Dict,
    chart_config: Dict,
    title: str
) -> Optional[RLImage]:
    """
    Generate a matplotlib chart and return as ReportLab Image.
    """
    try:
        fig, ax = plt.subplots(figsize=(6, 4))
        
        chart_type = chart_config.get('type', 'bar')
        data_points = chart_config.get('data', [])
        
        if not data_points:
            print(f"No data points for chart: {title}")
            plt.close(fig)
            return None
        
        # Extract labels and values based on data format
        labels = []
        values = []
        
        # Handle different data formats
        if isinstance(data_points, list) and len(data_points) > 0:
            first_point = data_points[0]
            
            if 'name' in first_point and 'value' in first_point:
                # Pie chart format: [{"name": ..., "value": ...}]
                labels = [str(p.get('name', '')) for p in data_points]
                values = [float(p.get('value', 0)) for p in data_points]
            elif 'x' in first_point and 'y' in first_point:
                # Bar/line/area format: [{"x": ..., "y": ...}]
                labels = [str(p.get('x', '')) for p in data_points]
                values = [float(p.get('y', 0)) for p in data_points]
            else:
                print(f"Unknown data format for chart: {title}")
                plt.close(fig)
                return None
        
        if not labels or not values:
            print(f"No valid data extracted for chart: {title}")
            plt.close(fig)
            return None
        
        # Limit data points for readability
        if len(labels) > 20 and chart_type != 'pie':
            labels = labels[:20]
            values = values[:20]
        elif len(labels) > 10 and chart_type == 'pie':
            labels = labels[:10]
            values = values[:10]
        
        # Generate chart based on type
        if chart_type == 'bar':
            ax.bar(labels, values, color='#3B82F6')
            ax.set_xlabel(chart_config.get('x_column', ''))
            ax.set_ylabel(chart_config.get('y_column', ''))
        elif chart_type == 'line':
            ax.plot(labels, values, marker='o', color='#3B82F6', linewidth=2)
            ax.set_xlabel(chart_config.get('x_column', ''))
            ax.set_ylabel(chart_config.get('y_column', ''))
            ax.grid(True, alpha=0.3)
        elif chart_type == 'area':
            ax.fill_between(range(len(values)), values, alpha=0.5, color='#3B82F6')
            ax.plot(range(len(values)), values, color='#1e40af', linewidth=2)
            ax.set_xticks(range(len(labels)))
            ax.set_xticklabels(labels)
            ax.set_xlabel(chart_config.get('x_column', ''))
            ax.set_ylabel(chart_config.get('y_column', ''))
            ax.grid(True, alpha=0.3)
        elif chart_type == 'pie':
            ax.pie(values, labels=labels, autopct='%1.1f%%', startangle=90)
            ax.axis('equal')
        else:
            # Default to bar
            ax.bar(labels, values, color='#3B82F6')
        
        ax.set_title(title, fontsize=12, fontweight='bold')
        if chart_type != 'pie':
            plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        
        # Save to bytes
        img_buffer = io.BytesIO()
        plt.savefig(img_buffer, format='png', dpi=150, bbox_inches='tight')
        img_buffer.seek(0)
        plt.close(fig)
        
        # Create ReportLab Image
        img = RLImage(img_buffer, width=5*inch, height=3.3*inch)
        return img
        
    except Exception as e:
        print(f"Error generating chart image: {e}")
        import traceback
        traceback.print_exc()
        return None



async def generate_pptx_report(
    dashboard_id: str,
    db: AsyncSession,
    output_dir: str = "data/reports"
) -> Dict:
    """
    Generate a complete PowerPoint business report.
    
    Returns:
        Dict with report_id, file_path, and metadata
    """
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Load dashboard and dataset
    result = await db.execute(select(Dashboard).where(Dashboard.id == dashboard_id))
    dashboard = result.scalar_one_or_none()
    if not dashboard:
        raise ValueError(f"Dashboard {dashboard_id} not found")
    
    result = await db.execute(select(Dataset).where(Dataset.id == dashboard.dataset_id))
    dataset = result.scalar_one_or_none()
    if not dataset:
        raise ValueError(f"Dataset {dashboard.dataset_id} not found")
    
    # Generate report ID and filename
    report_id = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    pptx_filename = f"{report_id}.pptx"
    pptx_path = os.path.join(output_dir, pptx_filename)
    
    # Create presentation
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)
    
    # Corporate blue/white theme colors
    BLUE = RGBColor(30, 64, 175)  # #1e40af
    DARK_BLUE = RGBColor(15, 32, 87)
    WHITE = RGBColor(255, 255, 255)
    LIGHT_GRAY = RGBColor(243, 244, 246)
    
    tiles = dashboard.tiles_json or []
    
    # SLIDE 1: Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank layout
    
    # Background
    background = slide.shapes.add_shape(
        1,  # Rectangle
        0, 0,
        prs.slide_width, prs.slide_height
    )
    background.fill.solid()
    background.fill.fore_color.rgb = BLUE
    background.line.fill.background()
    
    # Title
    title_box = slide.shapes.add_textbox(
        Inches(1), Inches(2.5),
        Inches(8), Inches(1.5)
    )
    title_frame = title_box.text_frame
    title_frame.text = "Business Intelligence Report"
    title_para = title_frame.paragraphs[0]
    title_para.font.size = Pt(44)
    title_para.font.bold = True
    title_para.font.color.rgb = WHITE
    title_para.alignment = PP_ALIGN.CENTER
    
    # Subtitle
    subtitle_box = slide.shapes.add_textbox(
        Inches(1), Inches(4.2),
        Inches(8), Inches(1)
    )
    subtitle_frame = subtitle_box.text_frame
    subtitle_frame.text = f"{dataset.name}\n{datetime.now().strftime('%B %d, %Y')}"
    subtitle_para = subtitle_frame.paragraphs[0]
    subtitle_para.font.size = Pt(20)
    subtitle_para.font.color.rgb = WHITE
    subtitle_para.alignment = PP_ALIGN.CENTER
    
    # Footer
    footer_box = slide.shapes.add_textbox(
        Inches(1), Inches(6.5),
        Inches(8), Inches(0.5)
    )
    footer_frame = footer_box.text_frame
    footer_frame.text = "Generated by Talking BI - Agentic AI Platform"
    footer_para = footer_frame.paragraphs[0]
    footer_para.font.size = Pt(12)
    footer_para.font.color.rgb = WHITE
    footer_para.alignment = PP_ALIGN.CENTER
    
    # SLIDE 2: Executive Summary
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    
    # Title
    title_box = slide.shapes.add_textbox(
        Inches(0.5), Inches(0.5),
        Inches(9), Inches(0.8)
    )
    title_frame = title_box.text_frame
    title_frame.text = "Executive Summary"
    title_para = title_frame.paragraphs[0]
    title_para.font.size = Pt(32)
    title_para.font.bold = True
    title_para.font.color.rgb = BLUE
    
    # Content
    insights_tile = next((t for t in tiles if t.get('type') == 'insights'), None)
    
    content_box = slide.shapes.add_textbox(
        Inches(0.5), Inches(1.5),
        Inches(9), Inches(5)
    )
    content_frame = content_box.text_frame
    content_frame.word_wrap = True
    
    if insights_tile and insights_tile.get('data'):
        insights_data = insights_tile['data']
        summary = insights_data.get('executive_summary', 'Analysis completed successfully.')
        confidence = insights_data.get('overall_confidence', 0)
        quality = insights_data.get('data_quality', 'medium')
        
        content_frame.text = summary
        content_para = content_frame.paragraphs[0]
        content_para.font.size = Pt(18)
        content_para.space_after = Pt(20)
        
        # Add quality indicator
        quality_para = content_frame.add_paragraph()
        quality_para.text = f"\nData Quality: {quality.title()} (Confidence: {confidence:.1f}%)"
        quality_para.font.size = Pt(14)
        quality_para.font.bold = True
        quality_para.font.color.rgb = DARK_BLUE
    else:
        content_frame.text = "This report provides comprehensive analysis of the dataset with key performance indicators, trends, correlations, and actionable recommendations."
        content_para = content_frame.paragraphs[0]
        content_para.font.size = Pt(18)
    
    # SLIDE 3: KPI Dashboard
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    
    # Title
    title_box = slide.shapes.add_textbox(
        Inches(0.5), Inches(0.5),
        Inches(9), Inches(0.8)
    )
    title_frame = title_box.text_frame
    title_frame.text = "Key Performance Indicators"
    title_para = title_frame.paragraphs[0]
    title_para.font.size = Pt(32)
    title_para.font.bold = True
    title_para.font.color.rgb = BLUE
    
    # KPI Table
    kpi_tiles = [t for t in tiles if t.get('type') == 'kpi']
    
    if kpi_tiles:
        rows = min(len(kpi_tiles) + 1, 11)  # Header + up to 10 KPIs
        cols = 4
        
        left = Inches(0.5)
        top = Inches(1.5)
        width = Inches(9)
        height = Inches(5)
        
        table = slide.shapes.add_table(rows, cols, left, top, width, height).table
        
        # Set column widths
        table.columns[0].width = Inches(3)
        table.columns[1].width = Inches(2)
        table.columns[2].width = Inches(2)
        table.columns[3].width = Inches(2)
        
        # Header row
        headers = ['Metric', 'Value', 'Change', 'Status']
        for col_idx, header in enumerate(headers):
            cell = table.cell(0, col_idx)
            cell.text = header
            cell.fill.solid()
            cell.fill.fore_color.rgb = BLUE
            
            para = cell.text_frame.paragraphs[0]
            para.font.size = Pt(14)
            para.font.bold = True
            para.font.color.rgb = WHITE
            para.alignment = PP_ALIGN.CENTER
        
        # Data rows
        for row_idx, kpi_tile in enumerate(kpi_tiles[:10], 1):
            kpi_info = kpi_tile.get('config', {})
            metric = kpi_tile.get('title', 'Unknown')
            value = kpi_info.get('value', 0)
            change = kpi_info.get('change', 0)
            
            # Metric name
            cell = table.cell(row_idx, 0)
            cell.text = metric
            cell.text_frame.paragraphs[0].font.size = Pt(12)
            
            # Value
            cell = table.cell(row_idx, 1)
            if isinstance(value, (int, float)):
                cell.text = f"{value:,.2f}"
            else:
                cell.text = str(value)
            cell.text_frame.paragraphs[0].font.size = Pt(12)
            cell.text_frame.paragraphs[0].alignment = PP_ALIGN.RIGHT
            
            # Change
            cell = table.cell(row_idx, 2)
            if change > 0:
                cell.text = f"↑ +{change:.1f}%"
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(220, 252, 231)  # Light green
            elif change < 0:
                cell.text = f"↓ {change:.1f}%"
                cell.fill.solid()
                cell.fill.fore_color.rgb = RGBColor(254, 226, 226)  # Light red
            else:
                cell.text = "—"
            cell.text_frame.paragraphs[0].font.size = Pt(12)
            cell.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
            
            # Status
            cell = table.cell(row_idx, 3)
            cell.text = "✓" if change >= 0 else "⚠"
            cell.text_frame.paragraphs[0].font.size = Pt(14)
            cell.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
    
    # SLIDES 4-7: Chart Slides (one chart per slide)
    chart_tiles = [t for t in tiles if t.get('type') in ['chart', 'bar', 'line', 'area', 'pie']]
    charts_added = 0
    
    for chart_tile in chart_tiles[:4]:  # Up to 4 charts
        try:
            chart_config = chart_tile.get('config', {})
            chart_title = chart_tile.get('title', 'Chart')
            
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            
            # Title
            title_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(0.5),
                Inches(9), Inches(0.8)
            )
            title_frame = title_box.text_frame
            title_frame.text = chart_title
            title_para = title_frame.paragraphs[0]
            title_para.font.size = Pt(28)
            title_para.font.bold = True
            title_para.font.color.rgb = BLUE
            
            # Generate chart image
            chart_img_path = await _generate_chart_for_pptx(
                {}, chart_config, chart_title, output_dir
            )
            
            if chart_img_path and os.path.exists(chart_img_path):
                # Add image to slide
                left = Inches(1)
                top = Inches(1.8)
                width = Inches(8)
                
                slide.shapes.add_picture(chart_img_path, left, top, width=width)
                charts_added += 1
                
                # Add insight caption if available
                if insights_tile and insights_tile.get('data'):
                    key_insights = insights_tile['data'].get('key_insights', [])
                    if charts_added <= len(key_insights):
                        caption_box = slide.shapes.add_textbox(
                            Inches(0.5), Inches(6.5),
                            Inches(9), Inches(0.8)
                        )
                        caption_frame = caption_box.text_frame
                        caption_frame.text = f"💡 {key_insights[charts_added - 1]}"
                        caption_para = caption_frame.paragraphs[0]
                        caption_para.font.size = Pt(12)
                        caption_para.font.italic = True
                
                # Clean up temp file
                try:
                    os.remove(chart_img_path)
                except:
                    pass
        except Exception as e:
            print(f"Error adding chart '{chart_title}' to PowerPoint: {e}")
            import traceback
            traceback.print_exc()
            continue
    
    # SLIDE 8: Root Cause Analysis (if available)
    root_cause_tile = next((t for t in tiles if t.get('type') == 'root_cause'), None)
    
    if root_cause_tile and root_cause_tile.get('data'):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        
        # Title
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.5),
            Inches(9), Inches(0.8)
        )
        title_frame = title_box.text_frame
        title_frame.text = "Root Cause Analysis"
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.color.rgb = BLUE
        
        # Content
        root_cause_data = root_cause_tile['data']
        metric = root_cause_data.get('metric', 'Unknown')
        change = root_cause_data.get('change_pct', 0)
        contributors = root_cause_data.get('top_contributors', [])
        narrative = root_cause_data.get('narrative', '')
        
        content_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(1.5),
            Inches(9), Inches(5.5)
        )
        content_frame = content_box.text_frame
        content_frame.word_wrap = True
        
        # Metric change
        p = content_frame.paragraphs[0]
        p.text = f"Metric: {metric} changed by {change:+.1f}%"
        p.font.size = Pt(18)
        p.font.bold = True
        p.space_after = Pt(15)
        
        # Top contributors
        if contributors:
            p = content_frame.add_paragraph()
            p.text = "Top Contributing Factors:"
            p.font.size = Pt(16)
            p.font.bold = True
            p.space_after = Pt(10)
            
            for i, contrib in enumerate(contributors[:5], 1):
                p = content_frame.add_paragraph()
                p.text = f"{i}. {contrib.get('segment', 'N/A')}: {contrib.get('contribution_pct', 0):+.1f}%"
                p.font.size = Pt(14)
                p.level = 1
                p.space_after = Pt(5)
        
        # Narrative
        if narrative:
            p = content_frame.add_paragraph()
            p.text = f"\n{narrative}"
            p.font.size = Pt(12)
            p.space_after = Pt(10)
    
    # SLIDE 9: Recommendations
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    
    # Title
    title_box = slide.shapes.add_textbox(
        Inches(0.5), Inches(0.5),
        Inches(9), Inches(0.8)
    )
    title_frame = title_box.text_frame
    title_frame.text = "Strategic Recommendations"
    title_para = title_frame.paragraphs[0]
    title_para.font.size = Pt(32)
    title_para.font.bold = True
    title_para.font.color.rgb = BLUE
    
    # Content
    recommendations_tile = next((t for t in tiles if t.get('type') == 'recommendations'), None)
    
    content_box = slide.shapes.add_textbox(
        Inches(0.5), Inches(1.5),
        Inches(9), Inches(5.5)
    )
    content_frame = content_box.text_frame
    content_frame.word_wrap = True
    
    if recommendations_tile and recommendations_tile.get('data'):
        recommendations = recommendations_tile['data'].get('recommendations', [])
        
        if recommendations:
            for i, rec in enumerate(recommendations[:3], 1):
                # Recommendation title
                p = content_frame.paragraphs[0] if i == 1 else content_frame.add_paragraph()
                p.text = f"{i}. {rec.get('action', 'N/A')}"
                p.font.size = Pt(16)
                p.font.bold = True
                p.space_after = Pt(8)
                
                # Details
                details = [
                    f"   • Expected Impact: {rec.get('expected_impact', 'N/A')}",
                    f"   • Timeline: {rec.get('timeline', 'N/A')}",
                    f"   • Risk Level: {rec.get('risk', 'N/A')}"
                ]
                
                for detail in details:
                    p = content_frame.add_paragraph()
                    p.text = detail
                    p.font.size = Pt(12)
                    p.space_after = Pt(3)
                
                # Spacing between recommendations
                if i < len(recommendations[:3]):
                    p = content_frame.add_paragraph()
                    p.text = ""
                    p.space_after = Pt(15)
        else:
            p = content_frame.paragraphs[0]
            p.text = "No recommendations generated."
            p.font.size = Pt(16)
    else:
        p = content_frame.paragraphs[0]
        p.text = "No recommendations data available."
        p.font.size = Pt(16)
    
    # Save presentation
    prs.save(pptx_path)
    
    # Save report metadata to database
    from database.models import Report
    report_record = Report(
        report_id=report_id,
        dashboard_id=dashboard_id,
        dataset_id=dataset.id,
        format="pptx",
        pptx_path=pptx_path,
        metadata_json={
            "slide_count": len(prs.slides),
            "charts_embedded": charts_added,
            "dataset_name": dataset.name
        }
    )
    db.add(report_record)
    await db.commit()
    
    return {
        "report_id": report_id,
        "file_path": pptx_path,
        "format": "pptx",
        "dashboard_id": dashboard_id,
        "dataset_name": dataset.name,
        "generated_at": datetime.now().isoformat(),
        "slide_count": len(prs.slides),
        "charts_embedded": charts_added
    }


async def _generate_chart_for_pptx(
    chart_data: Dict,
    chart_config: Dict,
    title: str,
    output_dir: str
) -> Optional[str]:
    """
    Generate a matplotlib chart and save as PNG for PowerPoint embedding.
    Returns path to saved image file.
    """
    try:
        fig, ax = plt.subplots(figsize=(8, 5))
        
        chart_type = chart_config.get('type', 'bar')
        data_points = chart_config.get('data', [])
        
        if not data_points:
            print(f"No data points for chart: {title}")
            plt.close(fig)
            return None
        
        # Extract labels and values based on data format
        labels = []
        values = []
        
        # Handle different data formats
        if isinstance(data_points, list) and len(data_points) > 0:
            first_point = data_points[0]
            
            if 'name' in first_point and 'value' in first_point:
                # Pie chart format: [{"name": ..., "value": ...}]
                labels = [str(p.get('name', '')) for p in data_points]
                values = [float(p.get('value', 0)) for p in data_points]
            elif 'x' in first_point and 'y' in first_point:
                # Bar/line/area format: [{"x": ..., "y": ...}]
                labels = [str(p.get('x', '')) for p in data_points]
                values = [float(p.get('y', 0)) for p in data_points]
            else:
                print(f"Unknown data format for chart: {title}")
                plt.close(fig)
                return None
        
        if not labels or not values:
            print(f"No valid data extracted for chart: {title}")
            plt.close(fig)
            return None
        
        # Limit data points for readability
        if len(labels) > 20 and chart_type != 'pie':
            labels = labels[:20]
            values = values[:20]
        elif len(labels) > 10 and chart_type == 'pie':
            labels = labels[:10]
            values = values[:10]
        
        # Generate chart based on type
        if chart_type == 'bar':
            ax.bar(labels, values, color='#3B82F6')
            ax.set_xlabel(chart_config.get('x_column', ''), fontsize=11)
            ax.set_ylabel(chart_config.get('y_column', ''), fontsize=11)
        elif chart_type == 'line':
            ax.plot(labels, values, marker='o', color='#3B82F6', linewidth=2.5, markersize=6)
            ax.set_xlabel(chart_config.get('x_column', ''), fontsize=11)
            ax.set_ylabel(chart_config.get('y_column', ''), fontsize=11)
            ax.grid(True, alpha=0.3)
        elif chart_type == 'pie':
            ax.pie(values, labels=labels, autopct='%1.1f%%', startangle=90, textprops={'fontsize': 10})
            ax.axis('equal')
        elif chart_type == 'area':
            ax.fill_between(range(len(values)), values, alpha=0.5, color='#3B82F6')
            ax.plot(range(len(values)), values, color='#1e40af', linewidth=2)
            ax.set_xticks(range(len(labels)))
            ax.set_xticklabels(labels)
            ax.set_xlabel(chart_config.get('x_column', ''), fontsize=11)
            ax.set_ylabel(chart_config.get('y_column', ''), fontsize=11)
            ax.grid(True, alpha=0.3)
        else:
            # Default to bar
            ax.bar(labels, values, color='#3B82F6')
        
        ax.set_title(title, fontsize=14, fontweight='bold', pad=15)
        if chart_type != 'pie':
            plt.xticks(rotation=45, ha='right', fontsize=9)
            plt.yticks(fontsize=9)
        plt.tight_layout()
        
        # Save to file
        temp_filename = f"chart_{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}.png"
        temp_path = os.path.join(output_dir, temp_filename)
        plt.savefig(temp_path, format='png', dpi=150, bbox_inches='tight')
        plt.close(fig)
        
        return temp_path
        
    except Exception as e:
        print(f"Error generating chart for PowerPoint: {e}")
        import traceback
        traceback.print_exc()
        return None

